import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";


const inter = Inter({subsets:["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className} flex flex-col min-h-screen`}
        >
          <Header/>
          <main className="flex-1 flex justify-center items-center p-4">{children}</main>
          <footer className="bg-gray-900 py-4">
              <div className="container mx-auto text-center px-4 text-gray-600">
                <p>KB Soultions copyright 2025</p>
              </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
